### ISSUE TITLE
win7中会黑屏

### ISSUE THREAD

**Issue by 87zrjojo** [zetaloop/keyviz#12]
在win7中打开软件后，全屏变黑，没法使用其它软件，不知此软件是否是不支持win7呢？

**Comment by zetaloop** [comment]
#8 已有反馈 win7 无法运行。

您要不试试安装原版？[mulaRahul/keyviz](https://github.com/mulaRahul/keyviz)
如果原版也不能运行的话，应该是软件不支持win7，我回去标注一下。
但如果原版可以运行的话，那可能是我的构建问题了。

**Comment by 87zrjojo** [comment]
测试原版这是一样的，win7存在黑屏问题，感谢。
&nbsp;


小@周
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年9月27日(星期五) 中午11:39
收件人: ***@***.***&gt;; 
抄送: "小@***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [zetaloop/keyviz] win7中会黑屏 (Issue #12)














 
#8 已有反馈 win7 无法运行。
 
您要不试试安装原版？mulaRahul/keyviz
 如果原版也不能运行的话，应该是软件不支持win7，我回去标注一下。
 但如果原版可以运行的话，那可能是我的构建问题了。

**Comment by zetaloop** [comment]
好的，我标注一下需要 Win10 以上
