### ISSUE TITLE
 resize the mouse cursor

### ISSUE THREAD

**Issue by cyy-2024** [zetaloop/keyviz#15]
Is it possible to add a feature to resize the mouse cursor, this cursor is a bit big for me at the moment.I would be very grateful if it was adopted!

**Comment by zetaloop** [comment]
本项目主要是 Keyviz 软件的中文界面汉化，如果希望添加新功能，请前往 [原 Keyviz 软件的仓库](https://github.com/mulaRahul/keyviz) 反馈。

此外，如果您指的是 这个光标👉<img width="20" alt="A cursor" src="https://github.com/user-attachments/assets/5b0ed8c4-082e-4320-811a-aba5938a1874"> 的大小，那么您可以直接在系统设置里调整。
例如，如果您是 Windows 11 系统，前往 设置 > 辅助功能 > 鼠标指针与触控，然后就能设置光标大小了。
其他系统的步骤类似。

**Comment by cyy-2024** [comment]
谢谢你：）的解答~~~我是新手，没有注意到是界面汉化仓库，非常感谢你的汉化！虽然我指的不是这个光标，但是这也是我第一次知道如何更改系统光标！谢谢！

**Comment by zetaloop** [comment]
> 谢谢你：）的解答~~~我是新手，没有注意到是界面汉化仓库，非常感谢你的汉化！虽然我指的不是这个光标，但是这也是我第一次知道如何更改系统光标！谢谢！

噢，那么你指的应该是鼠标点击的可视化动画👉<img width="77" alt="Snipaste_2024-10-18_22-46-30" src="https://github.com/user-attachments/assets/f1e38233-1fa4-4ac5-80e7-3fe2b36e826a"> 它的大小对吧，可以试试跟原作者反馈这个功能！

**Comment by cyy-2024** [comment]
ok~
