### ISSUE TITLE
win+L锁屏再解锁后，会其他按键前会一直附加win+L

### ISSUE THREAD

**Issue by xingling17777** [zetaloop/keyviz#17]
使用WIn+L锁屏，此时按空格键弹出密码输入框，解锁屏幕后后，在其他按键前会一直附加win+L+space，例如解锁屏幕后进入桌面时按下按键B，会变成win+L+space+B，锁屏键以及触发密码框的键会被一直记录。英文原版和汉化版都有这个问题。win11 64位专业版系统，23H2版本。

**Comment by zetaloop** [comment]
是已知问题。[mulaRahul/keyviz#264 (comment)](https://github.com/mulaRahul/keyviz/issues/264#issuecomment-2096185780)
一些按键（例如 Win+L）在触发后无法自动消失。等待原版修复。

临时解决方案：
如果觉得这个按键一直不消失比较烦人，可以单独按一下 Win 和 L，这样 keyviz 就能正确接收到这两个按键 "抬起" 的消息了。

**Comment by xingling17777** [comment]
谢谢，好过我之前用退出重新打开软件的方式。
