### ISSUE TITLE
显示历史记录了开关无效

### ISSUE THREAD

**Issue by zuiaiyutu** [zetaloop/keyviz#9]
显示历史记录哪里，不管是不显示，水平显示，垂直显示都无效。一直是水平显示

**Comment by zetaloop** [comment]
关掉设置窗口就能看到啦。

不显示历史：
<img width="170" alt="Snipaste_2024-09-11_19-30-23" src="https://github.com/user-attachments/assets/4d1745e5-f64c-472a-94ff-48e45a1e00c4">

垂直：
<img width="152" alt="Snipaste_2024-09-11_19-31-22" src="https://github.com/user-attachments/assets/db0eac6c-27fc-4cb2-a3b8-2854decd3fc2">

水平：
<img width="279" alt="Snipaste_2024-09-11_19-32-00" src="https://github.com/user-attachments/assets/e91fc0bf-38a1-4a95-99f4-08df58e75f11">

开着设置窗口的时候，可能是为了方便调整样式，它是一直只显示一次按键的。

**Comment by zuiaiyutu** [comment]
试了一下，确实是我搞错了
